#Make sure you have both <ep> in display_name and valid filename_regex. Other wise OKP will not match your ep number.
display_name="【喵萌Production】[LoveLive! 虹咲學園學園偶像同好會 完結篇 / Love Live! Nijigasaki Movie][<ep>][BDRip][<res>p][繁日雙語]"
group_name="[喵萌奶茶屋]"
poster="https://lain.bgm.tv/pic/cover/l/68/eb/442614_22L71.jpg"
about="https://github.com/Nekomoekissaten-SUB"
# Use ''' to avoid escape
filename_regex='''\]\[(?<ep>\d{2})\]\['''
# filename_regex="\\]\\[(?<ep>\\d{2}\\-\\d{2})\\]\\["
# filename_regex=""
resolution_regex='''\]\[(?<res>\d{3}|\d{4})p\]\['''
tags=["Anime", "Movie"]

[[intro_template]]
site="nyaa"
name="nekomoekissaten"

[[intro_template]]
site="acgrip"
name="喵萌奶茶屋"

[[intro_template]]
site="dmhy"
name="喵萌奶茶屋"

# [[intro_template]]
# site="bangumi"
# name="喵萌奶茶屋"

[[intro_template]]
site="acgnx_asia"
name="174"
